/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PersonalCard {
        "firstName": string;
        "lastName": string;
        "photo": string;
        "resume": string;
        "rol": string;
    }
    interface VideoPlayer {
        "provider": string;
        "source": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPersonalCardElement extends Components.PersonalCard, HTMLStencilElement {
    }
    var HTMLPersonalCardElement: {
        prototype: HTMLPersonalCardElement;
        new (): HTMLPersonalCardElement;
    };
    interface HTMLVideoPlayerElement extends Components.VideoPlayer, HTMLStencilElement {
    }
    var HTMLVideoPlayerElement: {
        prototype: HTMLVideoPlayerElement;
        new (): HTMLVideoPlayerElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "personal-card": HTMLPersonalCardElement;
        "video-player": HTMLVideoPlayerElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PersonalCard {
        "firstName"?: string;
        "lastName"?: string;
        "photo"?: string;
        "resume"?: string;
        "rol"?: string;
    }
    interface VideoPlayer {
        "provider"?: string;
        "source"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "personal-card": PersonalCard;
        "video-player": VideoPlayer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "personal-card": LocalJSX.PersonalCard & JSXBase.HTMLAttributes<HTMLPersonalCardElement>;
            "video-player": LocalJSX.VideoPlayer & JSXBase.HTMLAttributes<HTMLVideoPlayerElement>;
        }
    }
}
